version: '3.8'

services:
  api:
    build:
      context: ./api
    ports:
      - "8000:8000"
    env_file:
      - ./api/.env
    volumes:
      - ~/.aws:/root/.aws

  consumer:
    build:
      context: ./consumer
    volumes:
      - ~/.aws:/root/.aws
